//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenceExam.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestion
    {
        public long Id { get; set; }
        public long ExamId { get; set; }
        public long QuestionId { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
    }
}
